atmux: reduce to minimal session discovery logic

diff --git a/bin/atmux b/bin/atmux
--- a/bin/atmux
+++ b/bin/atmux
@@ -1,1 +1,29 @@
-atmux.py
+#!/usr/bin/env bash
+set -eo pipefail
+# NOTE: leaving out -o nounset, since it's not compatible with things like
+# virtualenvwrapper sourced by profile
+
+trap wtf INT TERM EXIT
+
+wtf()
+{
+    echo "$0: launch failed <press enter to exit>" >&2
+    read -r
+}
+
+if [ -z "${_PROFILE_LOADED-}" ]; then
+    # shellcheck source=/dev/null
+    source ~/.profile
+fi
+
+session=
+if [[ $# -gt 0 ]]; then
+    session=$1
+    shift
+fi
+
+if [[ -z "$session" ]]; then
+    session=$(basename "$(pwd)")
+fi
+
+exec tmux new-session -A -s "$session"
