Split topic merge logic from cmd_merge and cmd_squash.

diff --git a/bin/git-work b/bin/git-work
--- a/bin/git-work
+++ b/bin/git-work
@@ -154,6 +154,29 @@ rebase_check() {
 	done
 }
 
+merge_topic() {
+	rebase_check
+	[ -n "$rebase_state" ] && die "git work $cmd: rebase in progress"
+
+	tip=$1
+	if [ -z "$tip" ]; then
+		tip=$(git rev-parse HEAD)
+		tip_name=$(git symbolic-ref HEAD 2>/dev/null || git name-rev --always --name-only HEAD)
+		tip_name=${tip_name##*/}
+	else
+		tip_name=$1
+		tip=$(git rev-parse $tip)
+	fi
+	merge=work-merge
+	if git rev-parse --verify -q $merge > /dev/null; then
+		die "git work $cmd: branch ($merge) already exists, finish with that first"
+	fi
+	git checkout --no-track -b $merge $tip
+	if ! git rebase --onto master $local $merge; then
+		die "git work $cmd: rebase failed, you get to keep both pieces"
+	fi
+}
+
 nth_string () {
 	case "$1" in
 	*1[0-9]|*[04-9]) echo "$1"th;;
@@ -226,46 +249,13 @@ case "$cmd" in
 		fi
 		;;
 	merge)
-		rebase_check
-		[ -n "$rebase_state" ] && die "git work $cmd: rebase in progress"
-
-		tip=$1
-		if [ -z "$tip" ]; then
-			tip=$(git rev-parse HEAD)
-		fi
-		merge=work-merge
-		if git rev-parse --verify -q $merge > /dev/null; then
-			die "git work $cmd: branch ($merge) already exists, finish with that first"
-		fi
-		git checkout --no-track -b $merge $tip
-		if ! git rebase --onto master $local $merge; then
-			die "git work $cmd: rebase failed, you get to keep both pieces"
-		fi
+		merge_topic $1
 		git checkout master
 		git merge $merge
 		git branch -D $merge
 		;;
 	squash)
-		rebase_check
-		[ -n "$rebase_state" ] && die "git work $cmd: rebase in progress"
-
-		tip=$1
-		if [ -z "$tip" ]; then
-			tip=$(git rev-parse HEAD)
-			tip_name=$(git symbolic-ref HEAD 2>/dev/null || git name-rev --always --name-only HEAD)
-			tip_name=${tip_name##*/}
-		else
-			tip_name=$1
-			tip=$(git rev-parse $tip)
-		fi
-		merge=work-merge
-		if git rev-parse --verify -q $merge > /dev/null; then
-			die "git work $cmd: branch ($merge) already exists, finish with that first"
-		fi
-		git checkout --no-track -b $merge $tip
-		if ! git rebase --onto master $local $merge; then
-			die "git work $cmd: rebase failed, you get to keep both pieces"
-		fi
+		merge_topic $1
 		if [ -f $SQUASH_MSG ]; then
 			rm -f $SQUASH_MSG;
 		fi
