Display helpful rebase failure message.

diff --git a/bin/git-work b/bin/git-work
--- a/bin/git-work
+++ b/bin/git-work
@@ -238,7 +238,9 @@ case "$cmd" in
 			die "git work $cmd: branch ($merge) already exists, finish with that first"
 		fi
 		git checkout --no-track -b $merge $tip
-		git rebase --onto master $local $merge
+		if ! git rebase --onto master $local $merge; then
+			die "git work $cmd: rebase failed, you get to keep both pieces"
+		fi
 		git checkout master
 		git merge $merge
 		git branch -D $merge
@@ -265,7 +267,9 @@ case "$cmd" in
 		fi
 		make_squash_message $local $tip $tip_name > $SQUASH_MSG
 		git checkout --no-track -b $merge $tip
-		git rebase --onto master $local $merge
+		if ! git rebase --onto master $local $merge; then
+			die "git work $cmd: rebase failed, you get to keep both pieces"
+		fi
 		git checkout master
 		git merge --squash $merge
 		git branch -D $merge
